/* Generated By:JavaCC: Do not edit this line. parser_robotConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface parser_robotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SI = 5;
  /** RegularExpression Id. */
  int V1 = 6;
  /** RegularExpression Id. */
  int V2 = 7;
  /** RegularExpression Id. */
  int V3 = 8;
  /** RegularExpression Id. */
  int ENT = 9;
  /** RegularExpression Id. */
  int FIN = 10;
  /** RegularExpression Id. */
  int REP = 11;
  /** RegularExpression Id. */
  int VEC = 12;
  /** RegularExpression Id. */
  int DER = 13;
  /** RegularExpression Id. */
  int IZQ = 14;
  /** RegularExpression Id. */
  int GIR = 15;
  /** RegularExpression Id. */
  int RET = 16;
  /** RegularExpression Id. */
  int AV = 17;
  /** RegularExpression Id. */
  int ENTERO = 18;
  /** RegularExpression Id. */
  int MEQ = 19;
  /** RegularExpression Id. */
  int MAQ = 20;
  /** RegularExpression Id. */
  int DP = 21;
  /** RegularExpression Id. */
  int AP = 22;
  /** RegularExpression Id. */
  int CP = 23;
  /** RegularExpression Id. */
  int CO = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"Si\"",
    "\"s1\"",
    "\"s2\"",
    "\"s3\"",
    "\"entonces\"",
    "\"Fin\"",
    "\"Repite\"",
    "\"Veces\"",
    "\"derecha\"",
    "\"izquierda\"",
    "\"gira\"",
    "\"retrocede\"",
    "\"avanza\"",
    "<ENTERO>",
    "\"<\"",
    "\">\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
